env:
  browser: true
  es6: true
  mocha: true
  node: true
parser: "babel-eslint"
extends:
  - "eslint:recommended"
parserOptions:
  env:
    es6: true
  sourceType: "module"
rules:
  brace-style:
    - warn
    - 1tbs
  camelcase: off
  comma-dangle:
    - warn
    - always-multiline
  comma-style:
    - error
    - last
  complexity: error
  curly: warn
  eol-last:
    - error
    - always
  max-lines: off
  max-params:
    - error
    - 6
  no-duplicate-imports: error
  no-eq-null: error
  no-unused-vars:
    - off
    - argsIgnorePattern: "^_"
  no-eval: error
  no-implied-eval: error
  no-invalid-this: error
  no-shadow: error
  no-warning-comments:
    - warn
    - location: anywhere
      terms:
        - todo
        - fixme
  prefer-promise-reject-errors: error
  semi: error
